
slug = "issue-1"
number = 1
title = "Issue 1"

[[article]]
file = "1-first.md"
path = "/1-first"
title = "First article"
author = "josh_thompson"
cover = ""
pub_date = "2023-03-10"
publish = true
# Whether to publish the artice or not
featured = true
# When artices are reposted from the original source, 
# set a canonical property to help prevent duplicate content issues for search enginges
i18n.fr = { file = "1-first-fr.md", title = "Issue 1 Wooo", pub_date = "2022-03-10"}
i18n.fr = { file = "1-first-zh.md", title = "Issue 1 Wooo", pub_date = "2022-03-10"}



[[artice]]
file = "2-first.md"
path="2-first"
title = "First Second article"
author = "josh_thompson"
cover = ""
pub_date = "2023-03-10"
publish = true
# Whether to publish the artice or not
featured = true
# When artices are reposted from the original source, 
# set a canonical property to help prevent duplicate content issues for search enginges
